version: 2.1

setup: true
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Update a variable"
          command: "sed -n 's/{parallelism}/4/gi' .circleci/configtwo.yml"
      - run:
          name: "Echo the new config update."
          command: "cat .circleci/configtwo.yml"
      

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
