version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Get a random number!"
          command: "randomNumber=$(curl 'https://www.random.org/integers/?num=1&min=1&max=10&col=11&format=plain&base=10')"
      - run:
          name: "Update a variable - parallelism,  in this case."
          command: "sed 's/{parallelismVal}/$randomNumber/gi' .circleci/configtwo.yml > .circleci/newConfig.yml"
      - run:
          command: "cat .circleci/newConfig.yml"
      - continuation/continue:
          configuration_path: .circleci/newConfig.yml
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
