version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Update a variable - parallelism,  in this case."
          command: "sed 's/{parallelismVal}/4/gi' .circleci/configtwo.yml > .circleci/configtwo.yml"
      - continuation/continue:
          configuration_path: .circleci/configtwo.yml
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
